### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_match')

### ISSUE THREAD

**Issue by rgucciardi** [zacfilan/brimstone-recorder#64] opened 2021-09-08 02:51 UTC
[NextTest.zip](https://github.com/zacfilan/brimstone-recorder/files/7125427/NextTest.zip)

**Comment by patchworksapp** [comment] 2021-09-08 13:33
Can't replay this since you are using an autofiller/pasword manager. I suspect that may be the underlying issue.
Please, disable your autofillers and re-record/playback, and resubmit if you still can reproduce.
Also please paste the stack trace in the error next time too, I can't figure out the line from the title. :)
Closing for now.

Updated the documentation to reflect that password managers/autofillers should be disabled when using brimstone. 
https://github.com/zacfilan/brimstone-recorder/wiki/Playing#dos-and-donts
https://github.com/zacfilan/brimstone-recorder/wiki/Recording#dos-and-donts

**Closed by patchworksapp** 2021-09-08 13:33 UTC
